set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets rst_IBUF]

set_property PACKAGE_PIN W7 [get_ports op[0]]
set_property IOSTANDARD LVCMOS33 [get_ports op[0]]
set_property PACKAGE_PIN W6 [get_ports op[1]]
set_property IOSTANDARD LVCMOS33 [get_ports op[1]]
set_property PACKAGE_PIN U8 [get_ports op[2]]
set_property IOSTANDARD LVCMOS33 [get_ports op[2]]
set_property PACKAGE_PIN V8 [get_ports op[3]]
set_property IOSTANDARD LVCMOS33 [get_ports op[3]]
set_property PACKAGE_PIN U5 [get_ports op[4]]
set_property IOSTANDARD LVCMOS33 [get_ports op[4]]
set_property PACKAGE_PIN V5 [get_ports op[5]]
set_property IOSTANDARD LVCMOS33 [get_ports op[5]]
set_property PACKAGE_PIN U7 [get_ports op[6]]
set_property IOSTANDARD LVCMOS33 [get_ports op[6]]
set_property PACKAGE_PIN V7 [get_ports dot]
set_property IOSTANDARD LVCMOS33 [get_ports dot]

#set_property PACKAGE_PIN V7 [get_ports op[7]]
#set_property IOSTANDARD LVCMOS33 [get_ports op[7]]


set_property PACKAGE_PIN W19 [get_ports buttons[0]]
set_property IOSTANDARD LVCMOS33 [get_ports buttons[0]]
set_property PACKAGE_PIN T17 [get_ports buttons[1]]
set_property IOSTANDARD LVCMOS33 [get_ports buttons[1]]
set_property PACKAGE_PIN U17 [get_ports buttons[2]]
set_property IOSTANDARD LVCMOS33 [get_ports buttons[2]]
set_property PACKAGE_PIN T18 [get_ports buttons[3]]
set_property IOSTANDARD LVCMOS33 [get_ports buttons[3]]

set_property PACKAGE_PIN U18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN W4 [get_ports anode[3]]
set_property IOSTANDARD LVCMOS33 [get_ports anode[3]]
set_property PACKAGE_PIN V4 [get_ports anode[2]]
set_property IOSTANDARD LVCMOS33 [get_ports anode[2]]
set_property PACKAGE_PIN U4 [get_ports anode[1]]
set_property IOSTANDARD LVCMOS33 [get_ports anode[1]]
set_property PACKAGE_PIN U2 [get_ports anode[0]]
set_property IOSTANDARD LVCMOS33 [get_ports anode[0]]
set_property PACKAGE_PIN V17 [get_ports r]
set_property IOSTANDARD LVCMOS33 [get_ports r]
#set_property PACKAGE_PIN W14 [get_ports rstnum] #
#set_property IOSTANDARD LVCMOS33 [get_ports rstnum] 

set_property PACKAGE_PIN R2 [get_ports sw[0]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[0]]
set_property PACKAGE_PIN T1 [get_ports sw[1]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[1]]
set_property PACKAGE_PIN U1 [get_ports sw[2]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[2]]
set_property PACKAGE_PIN W2 [get_ports sw[3]]
set_property IOSTANDARD LVCMOS33 [get_ports sw[3]]

